/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>


int main(void)
{
    /* Loop forever */
    /* Debug and test code */
    /* 
    #include "../../hw/uc_hw/tim/tim.h"
    #include "../../hw/uc_hw/core_init/core_init.h"
    #include "../../hw/uc_hw/i2c/i2c.h"
    #include "stm32c0xx.h"
    core_init();
    TIM3_init_pwm();
    i2c1_init();
    aa();
    
	  for(;;)
    {
      bb();
    }
    */  
}


